# Generated by Django 5.2 on 2025-04-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(default="000000", max_length=50, unique=True),
        ),
    ]
