# Generated by Django 5.2 on 2025-04-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0004_remove_scanlog_product_remove_scanlog_scanned_data_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScanLog",
        ),
    ]
