# Generated by Django 5.2 on 2025-04-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_delete_scanlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
