# Generated by Django 5.2 on 2025-04-19 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_productactionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productactionlog",
            name="action",
            field=models.CharField(
                choices=[("add", "Add"), ("edit", "Edit"), ("delete", "Delete")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productactionlog",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
            ),
        ),
    ]
