# Generated by Django 5.2 on 2025-04-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_productactionlog_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productactionlog",
            name="product_name",
            field=models.CharField(default="Unknown Product", max_length=100),
        ),
        migrations.AddField(
            model_name="productactionlog",
            name="product_sku",
            field=models.CharField(default="Unknown SKU", max_length=50),
        ),
        migrations.AlterField(
            model_name="productactionlog",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
            ),
        ),
    ]
