# Generated by Django 5.2 on 2025-04-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_productactionlog_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productactionlog",
            name="product_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="productactionlog",
            name="product_sku",
            field=models.CharField(max_length=50),
        ),
    ]
