# Generated by Django 5.2 on 2025-04-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_productactionlog_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productactionlog",
            name="quantity_change",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productactionlog",
            name="threshold_change",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
