# Generated by Django 5.2 on 2025-04-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_productactionlog_quantity_change_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productactionlog",
            name="current_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productactionlog",
            name="current_threshold",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
