# Generated by Django 5.2 on 2025-04-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_productactionlog_current_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanhistory",
            name="source",
            field=models.CharField(default="scanner", max_length=50),
        ),
    ]
