# Generated by Django 5.2 on 2025-04-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productactionlog",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the product (nullable for deleted items)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="scanhistory",
            name="source",
            field=models.CharField(
                default="scanner",
                help_text="Origin of the scan (e.g., 'scanner', 'scan-from-add')",
                max_length=50,
            ),
        ),
    ]
