# Generated by Django 5.2 on 2025-05-01 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_product_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(default=datetime.date(2026, 5, 1)),
            preserve_default=False,
        ),
    ]
